### ISSUE TITLE
[Refactor]: R code does not adhere to style guide

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/FIMS#567]
### Refactor request

The R code in the FIMS repository has code that deviates from the style guide recommended in the collaborative workflow even though the code is being styled by a styler. 

### Tasks
- [x] parameter and object names should be snake_case, e.g., `n_years` not `nyears` in fimsframe.R and test-fimsframe.R (@MOshima-PIFSC)
- [x] determine if the usethis package should be suggested or imported (test moving it to suggests in a branch)
- ~~look for additional rules to add to the styler to catch these types of deviations~~
- [x] open an issue in the case-studies repo about removing FIMSFrameAge from case studies
- [x] #564 
- [x] #590 
- [x] function names should align with the guide rather than be a mix of snake_case and camelCase; issue NOAA-FIMS/collaborative_workflow#133 will need to be decided upon before this task can more forward
- [x] roxygen @params should be sentences with subsequent lines indented with two spaces.
- [x] roxygen titles should be less than 80 but preferably 60 characters in sentence case without a full stop
- [x] roxygen even though I advocated for it, it has not officially accepted to use {} around package names
- [x] roxygen paragraph entries should start on a new line, e.g., @description, @source, @format, and @return should not have text on the same line
- [x] roxygen R/data_mile1.R#L6 can be wrapped to be less than 80 characters per line
- [x] #565
- [x] `use_template` and `ui_stop` are being imported in [R/FIMS-package.R](https://github.com/NOAA-FIMS/FIMS/blob/97281c20ba697c66cbbbf5fe4f01241f79183676/R/FIMS-package.R#L8) but they are being called with `::` so there is no need to import them
- [x] use `utils::head()` rather than importing it
- [x] Remove other unused functions should be removed from the code base

### Path forward

@MOshima-PIFSC and @kellijohnson-NOAA will work on this in the m2-r-cleanup branch, where tasks will be completed in sub-feature branches, e.g., m2-r-cleanup-zzz, that are merged into the feature branch daily. Then a pull request will be submitted after style-r is rebased to main. We can work on one file at a time rather than one task at a time, then move onto the tasks that cross multiple files. The timeline for completion is May 17th, 2024.

**Comment by kellijohnson-NOAA** [comment]
@MOshima-PIFSC I have another PR open for you to check quickly. But beyond that, do you have time to complete the task above related to changing things in fimsframe.R and the associated test to use underscores to separate words/phrases. E.g., n_years instead of nyrs and n_ages instead of nages? I think that is our last remaining task for this issue aside from waiting guidance on if we can move usethis to a suggested package. If you don't have time I can do it next week as well. Have a great weekend.

**Comment by MOshima-PIFSC** [comment]
@kellijohnson-NOAA I can do those tasks. I'll start working on them this afternoon and finish up anything remaining Monday.
Thanks!

**Comment by kellijohnson-NOAA** [comment]
If you want to, feel free to just do them on top of the PR that you just approved or branch off of m2-r-cleanup-remove.
