### ISSUE TITLE
[Developer Issue]: M2 Quality control task list

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/FIMS#662]
### Description

This issue will be a collect all for small tasks that need to be completed for quality control after features are implemented in milestone 2. For example, @rklasky mentioned there are a few spelling mistakes in the code that need cleaned up. Feel free to edit this comment or post more comments below regarding small things that need to be done before our next release.
```[tasklist]
### Tasks
- [x] rename get_output() to not start with get because that is used in the accessors of S4 objects
- [x] Fix output of `get_output()` if `finalize()` has not been called, e.g., `Invalid request to "get_output". Please call finalize first.[1] ""` should not have [1] but it is not clear in the code why it is being printed because the c++ code is `"Invalid request to \"get_output()\". Please call finalize() first."` (Matthew)
- [x] Add Bayesian demo and other distribution tests, make this a Discussion (Kelli)
- [x] Review all R functions to identify which should be exposed to users with the `@export tag` and then group them in the `_pkgdown.yml` file
- [x] Document Rcpp functions with titles, e.g., `Rcpp::function("CreateTMBModel", &CreateTMBModel, "Initialize the FIMS/TMB model")`
- [x] Fix function names throughout to use camel case in the C++.
- [x] update initialize_fims() and make sure only length-comp data scenario works (Bai)
- [x] remove .vscode folder if we want to and add it to .gitignore (Matthew)
- [x] Ensure use :: for all packages other than FIMS, e.g., `methods::new()` in maturity vignette (Andrea)
- [x] Line 196 of rcpp_interface_base.hpp should be changed to `if (static_cast<size_t>(pos) == 0 || static_cast<size_t>(pos) > this->storage_m->size()) {` from `if (pos == 0 || pos > this->storage_m->size()) {`
- [ ] https://github.com/NOAA-FIMS/FIMS/issues/691
- [x] remove commented-out code, e.g., `// data_indicator<tmbutils::vector<Type> , Type> keep;`
- [x] Fix spacing in information.hpp `FIMS_INFO_LOG("Random effect size for distribution " + fims::to_string(d->id) + "is: " + fims::to_string(d->x.size()));` where it needs a space before is.
- [x] remove "TMB" from distribution class names and distribution files.
- [x] should be able to remove `library(TMB)` call from vignettes but this needs to be tested
- [x] fix data-raw/data_mile1.R so you can source the file from your working directory, right now it only works if you run it line by line (Bai)
- [x] change FIMSFrame functions to all start with `get_*()` like `get_data()` (Bai and Kelli)
- [x] Fix documentation for set_all_random, e.g., `.method("set_all_random", &ParameterVector::set_all_random, "Sets all Parameters within vector as estimable.")`
- [x] write tests for length (Nathan and Bai)
- [x] Edit authors, creators, and contributors in DESCRIPTION (Kelli)
- [x] Change `clear()` to nuke (Matthew)
- [x] Remove `size_t index_yf = year * population.nfleets + fleet_index;` from test_population_Unfished_Initial.cpp clang-tidy recognized it as not being used
- [x] Refactor information (Ron and Andrea)
- [x] document methods in R/fimsframe.R using @rdname like how it is done for m_lengthcomp (Meg)
- [x] Use `%in%` in R/fimsframe.R instances of `.data[["name"]] == fleet_name` (Meg)
- [x] in data-raw/data_mile1.R change `maindir` to main_dir` (Bai)
- [x] case studies should be ran every week and main should be checked every week, needs changes to the .github/workflows files (Ian/Jane/Kathryn)
- [x] Remove author name, email, and date created from C++ files (Ian/Jane/Kathryn)
- [x] Fix spelling of "sucess" to "success" in vignette/fims-demo (Matthew)
- [x] Fix spelling of "proirs" to "priors" (Matthew)
- [x] Change actions/checkout@v3 to v4 (Ian/Jane/Kathryn)
- [x] add call-spell-check.yml from {ghactions4r} into the FIMS GHA workflows (Ian/Jane/Kathryn)
- [x] exchange $ for [[""]] in R/distribution_formulas.R for all non-module calls (Kelli)
- [x] Add non vignettes/*.Rmd files to .gitignore
- [x] In information.hpp the exit(1) command is a bit heavy handed (imho)
- [x] In information.hpp valid_model never is used due to the exit(1) command
- [x] stop showing the data frames that are available in the vignette
- [x] add .gitignore to vignettes to ignore everything but .Rmd files
- [x] remove non-essential settings from fims-demo and use documentation or args() to display default settings (Bai)
- [x] fix C++ so the number of warnings when compiling is reduced to a minimal number (Matthew)
```

**Comment by k-doering-NOAA** [comment]
As a solution for spelling mistakes in the long term, there is a github action that runs the [spelling::spell_check_package()](https://docs.ropensci.org/spelling/#spell-check-a-package) in ghactions4r: https://nmfs-fish-tools.github.io/ghactions4r/reference/use_spell_check.html
